Proyecto/Proyecto/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('home.urls')),
]

Proyecto/home/urls.py
from django.conf.urls import include,url
from django.conf import settings
from django.conf.urls.static import static
from .views import (SignUp, Perfil_View, Perfil_Update, Friend_List, Community_List,Add_Friend,
	Delete_Friend, Register_Publication, Report_Publication, Score_Publication,
	Unscored_Publication, Register_Comment, Score_Comment)

urlpatterns = [
	url(r'^$', 'django.contrib.auth.views.login', {'template_name': 'home/index.html'}, name='login'),
	url(r'^cerrar/$', 'django.contrib.auth.views.logout_then_login', name = "logout" ),
	url(r'signup/', SignUp.as_view(), name='signup'),
	url(r'^perfil_view/$', Perfil_View.as_view(),name='perfil_view'),
	url(r'^update_perfil/(?P<pk>[\w-]+)/$', Perfil_Update.as_view(), name='perfil_update'),
	url(r'^friend_list/$', Friend_List.as_view(), name='friend_list'),
	url(r'^community_list/$', Community_List.as_view(), name='community_list'),
	url(r'^add_friend/(?P<pk>[\w-]+)/(?P<friend>[\w-]+)/$', Add_Friend, name='add_friend'),
	url(r'^delete_friend/(?P<pk>[\w-]+)/(?P<friend>[\w-]+)/$', Delete_Friend, name='delete_friend'),
	url(r'^register_publication/$', Register_Publication.as_view(), name='register_publication'),
	url(r'^report_publication/$', Report_Publication.as_view(), name='report_publication'),
	url(r'^score_publication/(?P<pk>[\w-]+)/$',Score_Publication , name='score_publication'),
	url(r'^unscored_publication/(?P<pk>[\w-]+)/$',Unscored_Publication , name='unscored_publication'),
	url(r'^detail_publication/(?P<pk>[\w-]+)/$', Register_Comment.as_view(), name='detail_publication'),
	url(r'^score_comment/(?P<publication>[\w-]+)/(?P<comment>[\w-]+)/$',Score_Comment , name='score_comment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyecto/home/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User

class Perfil(models.Model):
	user_perfil = models.OneToOneField(User)
	email = models.EmailField()
	image = models.ImageField(upload_to='perfil_Usuario/', blank=True, null=True, default='../static/user.png')
	friends = models.ManyToManyField("self", blank=True)

	#Metodo para devolder
	def __unicode__(self):
		return self.user_perfil.username

	def get_friends(self):
		return "\n , ".join([str(p.user_perfil) for p in self.friends.all()])

class Publication(models.Model):
	title = models.CharField(max_length=100)
	body = models.TextField()
	score = models.PositiveIntegerField(blank=True, null=True, default=0)
	unscored = models.PositiveIntegerField(blank=True, null=True, default=0)
	user = models.CharField(max_length=50)

	def __unicode__(self):
		return unicode(self.title)

class Comment(models.Model):
	comment = models.TextField()
	score = models.PositiveIntegerField(blank=True, null=True, default=0)
	user = models.CharField(max_length=50)
	publication = models.ForeignKey("Publication")

	def __unicode__(self):
		return unicode(self.comment)

Proyecto/home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Create your models here.
class User_form(UserCreationForm):
	email = forms.CharField(max_length=40)
	image = forms.ImageField(required = False)

Proyecto/home/views.py
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, ListView, UpdateView, TemplateView
from .models import Perfil, Publication, Comment
from django.core.urlresolvers import reverse_lazy
from .forms import User_form
from django.contrib.auth.models import User
from django.db.models import Count
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
# Create your views here.
class Perfil_View(TemplateView):
	template_name = 'home/perfil_detail.html'

	def get_context_data(self, **kwargs):
		context = super(Perfil_View, self).get_context_data(**kwargs)
		user = User.objects.get(username=self.request.user.username)
		context['object_list'] = Perfil.objects.filter(user_perfil=user)
		return context

class SignUp(CreateView):
	template_name = 'home/signup.html'
	form_class = User_form
	success_url = reverse_lazy('login')

	def form_valid(self, form):
		user = form.save()
		p = Perfil()
		p.user_perfil = user
		p.email = form.cleaned_data['email']
		p.image = form.cleaned_data['image']
		#p.is_staff=True
		p.save()
		return super(SignUp, self).form_valid(form)

class Perfil_Detail(DetailView):
	model = Perfil
	template_name = 'home/perfil_detail.html'

class Perfil_Update(UpdateView):
	model = Perfil
	fields = ['email','image']
	template_name = 'home/perfil_update.html'
	success_url = reverse_lazy('perfil_view')

class Friend_List(ListView):
	model = Perfil
	template_name = 'home/list_friends.html'

	def get_context_data(self, **kwargs):
		context = super(Friend_List, self).get_context_data(**kwargs)
		user = User.objects.get(username=self.request.user.username)
		context['object_list'] = Perfil.objects.filter(user_perfil=user)
		return context

class Community_List(ListView):
	model = Perfil
	template_name = 'home/list_community.html'

	def get_context_data(self, **kwargs):
		context = super(Community_List, self).get_context_data(**kwargs)
		user = User.objects.get(username=self.request.user.username)
		number = Perfil.objects.all().exclude(user_perfil=user).count()
		user_id = Perfil.objects.get(user_perfil=user)
		object_list = Perfil.objects.all().exclude(user_perfil=user)
		friend_list = Perfil.objects.filter(user_perfil=user)
		friendsExc = []
		communityExc = []
		nofriends = []

		for fr in friend_list:
			for f in fr.friends.all():
				friendsExc.append(f.user_perfil)

		for co in object_list:
			communityExc.append(co.user_perfil)

		for i in communityExc:
			if i in friendsExc:
				print '%s in both sets!' %(i)
			else:
				print '%s does not match!' %(i)
				nofriends.append(i)

		print nofriends
		return {'nofriends':nofriends,'number':number,'object_list':object_list, 'user_id':user_id}
# def Add_Friend(self, person, status):

def Add_Friend(request, pk, friend):
	if pk:
		p = Perfil.objects.get(id=pk)
		p.save()
		f = Perfil.objects.get(id=friend)
		p.friends.add(f)
	return HttpResponseRedirect('/friend_list/')

def Delete_Friend(request, pk, friend):
	if pk:
		p = Perfil.objects.get(id=pk)
		p.save()
		f = Perfil.objects.get(id=friend)
		p.friends.remove(f)
	return HttpResponseRedirect('/friend_list/')

class Register_Publication(CreateView):
	template_name = 'home/register_publication.html'
	model = Publication
	fields = ['title', 'body', 'user']
	success_url = reverse_lazy('report_publication')

class Report_Publication(ListView):
	template_name = 'home/report_publication.html'
	model = Publication

def Score_Publication(request, pk):
	if pk:
		p = Publication.objects.get(id=pk)
		counter = p.score
		if counter == None:
			counter = 0
		counter += 1
		p.score = counter
		p.save()

	return HttpResponseRedirect('/detail_publication/%s'%pk)

def Unscored_Publication(request, pk):
	if pk:
		p = Publication.objects.get(id=pk)
		counter = p.unscored
		if counter == None:
			counter = 0
		counter += 1
		p.unscored = counter
		p.save()

	return HttpResponseRedirect('/detail_publication/%s'%pk)

def Score_Comment(request, publication, comment):
	if publication and comment:
		c = Comment.objects.get(id=comment)
		counter = c.score
		if counter == None:
			counter = 0
		counter += 1
		c.score = counter
		c.save()

	return HttpResponseRedirect('/detail_publication/%s'%publication)

class Register_Comment(CreateView):
	template_name = 'home/detail_publication.html'
	model = Comment
	fields = ['comment', 'user', 'publication']
	success_url = reverse_lazy('report_publication')

	def get_context_data(self, **kwargs):
		context = super(Register_Comment, self).get_context_data(**kwargs)
		context['object'] = Publication.objects.get(id=self.kwargs['pk'])
		context['comment_list'] = Comment.objects.filter(publication=self.kwargs['pk'])
		return context

Proyecto/home/templates/home/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>

<link href="{% static 'bootstrap/css/bootstrap.min.css' %}"rel="stylesheet" media="screen">
<link rel="stylesheet" href="{% static 'bootstrap/css/blog.css' %}">
<script src="/static/bootstrap/js/jquery-1.12.2.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/bootstrap/js/jquery.js"></script>
<link rel="stylesheet" href="/static/pure-release-0.6.0/pure-min.css">
<!-- JAVASCRIPTS -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.backtotop.js' %}"></script>
<script src="{% static 'js/jquery.mobilemenu.js' %}"></script>
<!-- IE9 Placeholder Support -->
<script src="{% static 'js/jquery.placeholder.min.js' %}"></script>
<!-- / IE9 Placeholder Support -->
<link rel="stylesheet" type="text/css" media="all" href="{% static 'styles/layout.css' %}"/>

<meta charset="utf-8">
<!--<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">  -->

</head>
<body id="top">
{% if user.is_authenticated %}
<<div class="bgded" style="background-image:url({% static 'media/FondoPrincipal.jpg' %});">
<div class="wrapper overlay">
  <header id="header" class="hoc clear">
        <nav id="mainav" class="clear">
          <ul class="clear">
            <li class="active"><a href="{% url 'login' %}">Inicio</a></li>
            <li><a class="drop" href="#">Comunidad</a>
              <ul>
                <li><a href="{% url 'community_list' %}">TODOS LOS USUARIOS</a></li>
                <li><a href="{% url 'friend_list' %}">MIS AMIGOS</a></li>
              </ul>
            </li>
            <li><a class="drop" href="#">Publicaciones</a>
              <ul>
                <li><a href="{% url 'report_publication' %}">TODAS LAS PUBLICACIONES</a></li>
                <li><a href="{% url 'register_publication' %}">PUBLICAR ALGO NUEVO</a></li>
              </ul>
            </li>
            <li><a class="drop" href="#">{{user.username}}</a>
              <ul>
                <li><a href="{% url 'perfil_view' %}">Perfil<img src="{{ get_image_profile }}" width="15px" height="15px"  class="img-circle"></a></li>
                <li><a href="{% url 'logout' %}">Cerrar sesion</a></li>
              </ul>
            </li>
          </nav>

      <div id="logo">
              <!-- ################################################################################################ -->
          <h1><a href="#">Comunidad Universitaria</a></h1>
          <p>tu principal fuente de tareas e investigaciones comprobadas</p>
              <!-- ################################################################################################ -->
      </div>
    </div>
{% else %}
<div class="bgded" style="background-image:url({% static 'media/FondoPrincipal.jpg' %});">
<div class="wrapper overlay">
  <header id="header" class="hoc clear">
        <nav id="mainav" class="clear">
          <ul class="clear">
            <li><a href="{% url 'login' %}"> INICIO</a></li>
            <li><a href="{% url 'signup' %}"> REGISTRARSE</a></li>
          </ul>

          </nav>
          <div id="logo">
            <!-- ################################################################################################ -->
            <h1><a href="#">Comunidad Universitaria</a></h1>
            <p>tu principal fuente de tareas e investigaciones comprobadas</p>
            <!-- ################################################################################################ -->
          </div>
  </div>

{% endif %}
<!-- ################################################################################################ -->

     <div id="pageintro" class="hoc clear">
       <!-- ################################################################################################ -->
       <article>
         <div class="introtxt">
           <p class="font-xs nospace">Bienvenido a nuestra comunidad de usuarios universitarios</p>
           <h2 class="heading">Presentacion</h2>
           <p>En esta pagina encontraras informacion y documentos con respecto a Tareas, Investigaciones, Examenes y mas con su fuente bibliografica verificada y comprobada que no sea plageada de otro sitio.</p>
         </div>
         <footer>
           <ul class="nospace inline pushright">
           </ul>
         </footer>
       </article>
       <!-- ################################################################################################ -->
     </div>


<a id="backtotop" href="#top"><i class="fa fa-chevron-up"></i></a>

</body>
</html>
{% block content %}
{% endblock %}

<div class="wrapper row4">
  <footer id="footer" class="hoc clear">
    <!-- ################################################################################################ -->
    <div class="one_half first">
      <h6 class="title">Contactanos</h6>
      <ul class="nospace linklist contact">
        <li><i class="fa fa-envelope-o"></i>diego.saldana16@tectijuana.edu.mx</li>
        <li><i class="fa fa-envelope-o"></i>jose.beltran@tectijuana.edu.mx</li>
        <li><i class="fa fa-envelope-o"></i>edgar.castillo@tectijuana.edu.mx</li>
      </ul>
    </div>

    <div class="one_half">
      <h6 class="title">Escribenos un correo</h6>
      <p class="btmspace-30">Nos gustaria saber tu opinion respecto al sitio, si cumple o no tus espectativas y en que se puede mejorar</p>
  <!--    <form method="post" action="#">
        <fieldset>
          <legend>Newsletter:</legend>
          <input class="btmspace-15" type="text" value="" placeholder="Nombre">
          <input class="btmspace-15" type="text" value="" placeholder="Correo">
          <input class="btmspace-15" type="text" value="" placeholder="Tu mensaje">
          <button type="submit" value="submit">Enviar</button>
        </fieldset>
      </form>  -->
    </div>

    <!-- ################################################################################################ -->
  </footer>
</div>

<div class="wrapper row5">
  <div id="copyright" class="hoc clear">
    <!-- ################################################################################################ -->
    <p class="fl_left">Copyright &copy; 2017 - Todos los derechos reservados - <a href="#">Comunidad Universitaria</a></p>
    <p class="fl_right">Materia<a target="_blank" href="http://127.0.0.1:8000/" title=" ">Programacion Web</a></p>
    <!-- ################################################################################################ -->
  </div>
</div>

Proyecto/home/templates/home/detail_publication.html
{% extends 'home/base.html' %}
{% block title %}Extra{% endblock %}
{% block content %}
<div class="contenido">
	<h2>{{ object.title }}</h2>
	<h4>{{ object.body}}</h4>
	<h5>By: {{ object.user }}</h5>
	<h5> {{object.score}} Me gusta {{object.unscored}} No me gusta</h5>
	<a  href="/score_publication/{{object.pk}}/" role="button" class="btn btn-default">
		<span class="glyphicon glyphicon-heart"></span> Me gusta</a>
	<a  href="/unscored_publication/{{object.pk}}/" role="button" class="btn btn-default">
		<span class="glyphicon glyphicon-thumbs-down"></span> No me gusta</a>
	<br></br>
	<h4> Comentarios</h4>

	{% for comment in comment_list%}
	<h5>{{comment.user}}: {{comment.comment}} <a href="/score_comment/{{object.pk}}/{{comment.pk}}/" role="button" class="btn btn-default">{{comment.score}} <span class="glyphicon glyphicon-thumbs-up"></span></a></h5>
	{% endfor %}

	<form method ='POST' class="pure-form pure-form-aligned">
		{% csrf_token %}
		<p><textarea cols="40" id="id_comment" name="comment" rows="2">
		</textarea></p>
		<input id="id_user" maxlength="50" name="user" type="hidden" value="{{ user.username }}" />
		<input id="id_publication" maxlength="50" name="publication" type="hidden" value="{{object.id}}"/>

  		<button type="submit" class="pure-button pure-button-active" >Publicar <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></button>
    	<button type="reset" class="pure-button pure-button-active" >Cancelar <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
  </form>
</div>
{% endblock content%}

Proyecto/home/templates/home/index.html
{% extends 'home/base.html' %}
{% block title %}Index{% endblock %}
{% block content %}
{% if user.is_authenticated %}
 <div class="div-title">
  
  <h1>Bienvenido a nuestra pagina {{user.username}}</h1>

 </div>

{% else %}
<div class="div-title">
  <h1>Log In</h1>
 </div>
 <br></br>
 <div class="div-align">
  <form method ='POST' class = "form-horizontal" role = "form">
    {% csrf_token %}
      <div class = "form-group">
          <label for = "fullname"  align="center" class = "col-sm-2 control-label">Nombre de usuario</label>
          <div class = "col-sm-3">
            <input type = "text" name="username" class = "form-control" autocomplete="off">
          </div>
       </div>
      <div class = "form-group">
          <label for ="password" class = "col-sm-2 control-label">Contraseña</label>
          <div class = "col-sm-3">
            <input type = "password" name="password" class = "form-control">
          </div>
        </div>


      <div class = "form-group">
          <div class = "col-sm-offset-2 col-sm-10">
            <button type="submit" type="button" class = "btn btn-default">Iniciar sesion</button>
            <button type="reset" type="button" class = "btn btn-default">Cancelar</button>
        </div>
      </div>
</form>
</div>
{% endif %}
{% endblock %}

Proyecto/home/templates/home/list_community.html
{% extends 'home/base.html'%}
{% block title %}Criticas{% endblock%}
{% block content %}
<h2>Comunidad({{number}})</h2>

{% for item in object_list %}
	{% if item.user_perfil in nofriends %}
	<tr>
		<div>
		  <td><img src="http://127.0.0.1:8000/media/{{item.image}}" width="100px" height="100px" class="img-rounded"></td>
		  <th>{{ item.user_perfil }}</th>
		  <th><a  href="/add_friend/{{user_id.pk}}/{{item.pk}}/" role="button" class="btn btn-default">
		  <span class="glyphicon glyphicon-plus"></span> Agregar amigos</a></th>
		</div>
	</tr>
	{% else %}
		<tr>
			 <div>
		     <td><img src="http://127.0.0.1:8000/media/{{item.image}}" width="100px" height="100px" class="img-rounded"></td>
		     <th>{{ item.user_perfil }}</th>
		     <th><a  href="/delete_friend/{{user_id.pk}}/{{item.pk}}/" role="button" class="btn btn-default">
		     <span class="glyphicon glyphicon-ok"></span> Amigos</a></th>
			 </div>
	  </tr>
	{% endif %}
{% endfor %}

{% endblock content%}

Proyecto/home/templates/home/list_friends.html
{% extends 'home/base.html'%}
{% block title %}Criticas{% endblock%}
{% block content %}
{% for item in object_list%}
<h2>Tus amigos({{item.friends.count}})</h2>
<!--table id="TableForm" class="TableForm pure-form pure-form-aligned"-->

	{% for p in item.friends.all %}
	<tr>
		<div>
		  <td><img src="http://127.0.0.1:8000/media/{{p.image}}" width="100px" height="100px" class="img-rounded"></td>
		  <th>{{ p.user_perfil }}</th>
		  <th><a  href="/delete_friend/{{item.pk}}/{{p.pk}}/" role="button" class="btn btn-default">
		  <span class="glyphicon glyphicon-remove"></span> Eliminar</a></th>
		</div>
	</tr>
	{% endfor %}
{% endfor %}

{% endblock content%}

Proyecto/home/templates/home/perfil_detail.html
{% extends 'home/base.html' %}
{% block title %}Index{% endblock %}
{% block content %}
<h6 >Perfil de usuario</h6>
{% for item in object_list%}
<tr>
	<td><img src="http://127.0.0.1:8000/media/{{item.image}}" width="10%" class="img-circle"></td>
</tr>

<div class="wrapper row4">
    <!-- ################################################################################################ -->
    <div class="one_half">
      <ul class="nospace linklist contact">
        <li><i class="fa fa fax"></i>Nombre de usuario:   {{ item.user_perfil }}</li>
        <li><i class="fa fa fax"></i>Correo electronico:   {{item.email }}</li>
        <li><i class="fa fa fax"></i>Contraseña: ***** </li>
				<td><a href="/update_perfil/{{item.pk}}/" role="button" class="btn btn-default">Editar informacion</a>
      </ul>
    </div>
{% endfor %}
{% endblock %}

Proyecto/home/templates/home/perfil_update.html
{% extends 'home/base.html' %}
{% block title %}Index{% endblock %}
{% block content %}
<h1>Actualizar tus datos de usuario</h1>
<h3>*El nombre de usuario y contraseña no se pueden cambiar</h3>
<form method="POST" enctype="multipart/form-data" id="TableForm" class="TableForm pure-form pure-form-aligned" class="pure-input-rounded">
{% csrf_token %}
{{ form.as_p}}
<div>
  <button type="submit" class="btn btn-default">Actualizar<span class="glyphicon glyphicon-ok" aria-hidden="true">
</div>
</form>
{% endblock %}

Proyecto/home/templates/home/register_publication.html
{% extends 'home/base.html' %}
{% block title %}Index{% endblock %}
{% block content %}
{% if user.is_authenticated %}
<div class="div-title">
  <h1>Nueva publicacion</h1>
 </div>
<div class="div-align">
	<form method ='POST' class="pure-form pure-form-aligned">
		{% csrf_token %}
		<p><label for="id_title">Titulo:</label> <input id="id_title" maxlength="100" name="title" type="text" /></p>
		<p><label for="id_body">Descripcion:</label> <textarea cols="40" id="id_body" name="body" rows="10">
		</textarea></p>
		<input id="id_user" maxlength="50" name="user" type="hidden" value="{{ user.username }}" /></p>

  		<button type="submit" class="pure-button pure-button-active">Publicar <span class="glyphicon glyphicon-ok" aria-hidden="true"></span></button>
    	<button type="reset" class="pure-button pure-button-active">Cancelar <span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
  </form>
</div>
{% else %}
{% endif %}
{% endblock %}

Proyecto/home/templates/home/report_comment.html
{% extends 'home/base.html' %}
{% block title %}Extra{% endblock %}
{% block content %}
{% for item in object_list%}
<ul>
<div class="contenido" >
	<a  href="/register_comment/{{item.pk}}/">
	<h2>{{ item.title }}</h2></a>
	<h4>{{ item.body}}</h4>
	<h5>Usuario: {{ item.user }}</h5>
	<h5> {{item.score}} Me gusta {{item.unscored}} No me gusta</h5>
	<a  href="/score_publication/{{item.pk}}/" role="button" class="btn btn-default">
		<span class="glyphicon glyphicon-heart"></span> Me gusta</a>
	<a  href="/unscored_publication/{{item.pk}}/" role="button" class="btn btn-default">
		<span class="glyphicon glyphicon-thumbs-down"></span> No me gusta</a>
</div>
</ul>
{% endfor %}
{% endblock %}

Proyecto/home/templates/home/report_publication.html
{% extends 'home/base.html' %}
{% block title %}Extra{% endblock %}
{% block content %}
{% for item in object_list%}
<ul>
<div class="contenido" >
	<a  href="/detail_publication/{{item.pk}}/">
	<h2>{{ item.title }}</h2></a>
	<h4><strong>{{ item.body}}</h4></strong>
	<h5>By: <strong>{{ item.user }}</h5></strong>
	<h5> {{item.score}} Me gusta {{item.unscored}} No me gusta</h5>

</div>
</ul>
{% endfor %}
{% endblock %}

Proyecto/home/templates/home/reporte_perfil.html
{% extends 'home/base.html'%}
{% block title %}Criticas{% endblock%}
{% block content %}
 <div class="div-content">
<div class="panel panel-default">
  <div class="panel-heading">Usuarios</div>
  <div class="panel-body">

<table class="table">
<tr>
	<th>Nombre</th>
	<th>Foto</th>
	<th>Correo Electronico</th>
</tr>
{% for item in object_list%}
<tr>
		<td>{{ item.user_perfil }}</td>
		<td><img src="http://127.0.0.1:8000/media/{{item.image}}" width="45px"></td>
		<td>{{item.correo_electronico}}</td>
</tr>
{% endfor %}
</table>
</div>
</div>
</div>
{% endblock content%}

Proyecto/home/templates/home/signup.html
{% extends 'home/base.html' %}
{% block content %}
<title>Registrate</title>
<div class="div-title">
	<h2>Registrarse</h2>
</div>
<div class="div-align">
<form method="POST" class="pure-form" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p}}
    <button type="submit" class="btn btn-default">Registrar<span class="glyphicon glyphicon-ok" aria-hidden="true">
    </span></button>
    <button type="reset" class="btn btn-default">Cancelar<span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
</form>
</div>
{% endblock %}